spring.application.name=triviayallah
server.port=0
spring.datasource.url=jdbc:mysql://localhost:3306/ques
spring.datasource.username=root
spring.datasource.password=Tokyoraven
spring.jpa.hibernate.ddl-auto=update
