spring.application.name=triviayallah
spring.datasource.url=jdbc:${API_KEY}
spring.datasource.username=${USER_NAME}
spring.datasource.password=${DB_PASSWORD}
server.port=${PORT:9090}
spring.jpa.hibernate.ddl-auto=update

